config/routes.rb
Rails.application.routes.draw do
  root 'hello#index'
  post 'orders/:id' => 'orders#show',as: 'order'
  post 'orders/:id/edit' => 'orders#edit', as:'edit_order'
  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]

  devise_for :requesters, controllers: {
    sessions:       'requesters/sessions',
    passwords:      'requesters/passwords',
    registrations:  'requesters/registrations'
  }
  resources :requesters, only: [:index, :show, :edit, :update]
  

  resources :orders do
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :rooms, :only => [:create, :show] do
  resources :messages, :only => [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :requester
  belongs_to :student
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :order
  belongs_to :student
  validates_uniqueness_of :order_id, scope: :student_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :order
  belongs_to :requester

  validates_uniqueness_of :order_id, scope: :requester_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :requester
    has_many :likes, dependent: :destroy
    has_many :liked_requesters, through: :likes, source: :requester
    has_many :favorites, dependent: :destroy
    has_many :favorited_students, through: :favorites, source: :student
    mount_uploader :image, ImageUploader
end

app/models/receive.rb
class Receive < ApplicationRecord
  belongs_to :order
  belongs_to :student
  validates_uniqueness_of :order_id, scope: :student_id
end

app/models/requester.rb
class Requester < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_orders, through: :likes, source: :order
  has_many :rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def already_liked?(order)
    self.likes.exists?(order_id: order.id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_orders, through: :likes, source: :order
  has_many :rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_orders, through: :favorites, source: :order

  def already_liked?(order)
    self.likes.exists?(order_id: order.id)
  end

  def already_favorited?(order)
    self.favorites.exists?(order_id: order.id)
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_requester.likes.create(order_id: params[:order_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(order_id: params[:order_id], requester_id: current_requester.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    def index
        if requester_signed_in?
            @requesters = Requester.all
            @students = Student.all
            rooms = current_requester.rooms
            @requester_ids = []
            @student_ids = []
            rooms.each do |r|
                @student_ids << r.student_id
            end
        elsif student_signed_in?
            @students = Student.all
            @requesters = Requester.all
            rooms = current_student.rooms
            @student_ids = []
            @requester_ids = []
            rooms.each do |r|
                @requester_ids << r.requester_id
            end
        end

        @orders = Order.all
        if params[:search] == nil
            @orders= Order.all.page(params[:page]).per(10)
        elsif params[:search] == ''
            @orders= Order.all.page(params[:page]).per(10)
        elsif params[:search] == 'order.id'
            @orders= Order.where(id, params[:search]).page(params[:page]).per(10)
        else
            @orders = Order.where("body LIKE ? ",'%' + params[:search] + '%')
        end
    end

    def new
        @order = Order.new
    end

    def create
        order = Order.new(order_params)
        order.requester_id = current_requester.id
        if order.save!
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end

    def show
        @order = Order.find(params[:id])
    end

    def edit
        @order = Order.find(params[:id])
    end

    def update
        order = Order.find(params[:id])
        if order.update(order_params)
        redirect_to :action => "show", :id => order.id
        else
        redirect_to :action => "new"
        end
    end

    def destroy
        order = Order.find(params[:id])
        order.destroy
        redirect_to action: :index
    end
    
    private
    def order_params
        params.require(:order).permit(:body, :title, :image, :place, :datefrom, :dateto, :people, :job)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end

    def link
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/requesters_helper.rb
module RequestersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/orders/edit.html.erb
<%= form_for @order do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, :size => 160 %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "Edit" %>
  <% end %>

app/views/orders/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<h1>依頼一覧</h1>

<% if requester_signed_in? %>
~<%= current_requester.name %>がログインしてます~
<%= button_to 'ログアウトはこちら', destroy_requester_session_path, method: :delete %>
<% elsif student_signed_in? %>
~<%= current_student.name %>がログインしてます~
<%= button_to 'ログアウトはこちら', destroy_student_session_path, method: :delete %>
<% end %>

<% if requester_signed_in? %>
<%= button_to "マイページ", requester_path(current_requester.id) %>　
<% elsif student_signed_in? %>
<%= button_to "マイページ", student_path(current_student.id) %>
<% end %>

<br>
<%= page_entries_info @orders %>
<div class="orders-container", class: "col-md-12 form-control">
    <% @orders.each do |o| %>
        <div class="order">
            <div class="main-box">
                
                <div class="left-container", class: "col-md-12 form-control">
                    <a href="/requesters/<%= o.requester.id %>"><%= o.requester.name %></a><br>
                    <h4><%= o.title %></h4><br>
                    <p><%= o.body %></p><br>
                    <%= o.place %><br>
                    <%= o.datefrom %>～<%= o.dateto %><br>
                    <%= o.job %><br>
                    <p class="time"><%= o.created_at %></p>
                </div>
                <div class="right-container">
                    
                    <% if requester_signed_in? && current_requester.id == o.requester_id %>
                        <%= button_to "依頼詳細", order_path(o.id) %>
                        <%= button_to "編集する", edit_order_path(o.id) %>
                        <%= button_to "依頼を取り消す", order_path(o.id), method: :delete %>
                    <% end %> 
                </div>
            </div>
        </div>


        <% if requester_signed_in? %>
            <% if current_requester.already_liked?(o) %>
                <%= button_to order_like_path(id: o.id, order_id: o.id), method: :delete do %>
                    いいねを取り消す
                <% end %>
            <% else %>
                <%= button_to order_likes_path(id: o.id, order_id: o.id), method: :post do %>
                    いいね
                <% end %>
            <% end %>
        <%= o.likes.count %>
        <% else %>
            <p>いいねされた数</p></i><%= o.likes.count %>
        <% end %>

        <% if student_signed_in? %>
            <% if current_student.already_favorited?(o) %>
                <%= button_to order_favorite_path(id: o.id, order_id: o.id), method: :delete do %>
                    <p>受注を取り消す</p><%= o.favorites.count %>
                <% end %>
            <% else %>
                <%= button_to order_favorites_path(id: o.id, order_id: o.id), method: :post do %>
                    <p>受注</p><%= o.favorites.count %>
                <% end %>
            <% end %>
        <% else %>
            <p>受注した数</p><%= o.favorites.count %>
        <% end %>

        <%= image_tag o.image_url, size: "250x200" if o.image? %>
    
    <% end %>
</div>

<%= paginate @orders %>
<br>
<h2>DM簡易版</h2>
<br>

<% @students.each do |student| %>
    <%= student.name %>
    <% if @student_ids.include?(student.id) %>
        <br>
        <%= button_to "チャットへ", room_path(current_requester.rooms.find_by(student_id: student.id)) %><br>
    <% else %>
        <%= form_for Room.new do |f| %>
            <%= f.hidden_field :student_id, :value => student.id %>
            <%= f.submit %>
        <% end %>
    <% end %>
<% end %>

<% @requesters.each do |requester| %>
    <%= requester.name %>
    <% if @requester_ids.include?(requester.id) %>
        <br>
        <%= button_to "チャットへ", room_path(current_student.rooms.find_by(requester_id: requester.id)) %><br>
    <% else %>
        <%= form_for Room.new do |f| %>
            <%= f.hidden_field :requester_id, :value => requester.id %>
            <%= f.submit %>
        <% end %>
    <% end %>
<% end %>

app/views/orders/new.html.erb


<p><h1 class="text-center font-weight-bold pt-5">新規依頼</h1><p>
    <%= form_for @order do |f| %>
    <div class="col-md-10" pt-5>
        <h4><%= f.label :タイトル %></h4>
        <p><small>商大生の目を引くようなタイトルにしてみましょう。例：冷蔵庫が重くて運べない！</small></p>
        <%= f.text_field :title, :size => 160, class: "col-md-8 form-control", placeholder: "一言で概要を端的に書いてください。" %><br>
        <h4><%= f.label :依頼内容 %></h4>
        <p><small>「何をしてほしいのか？」をしっかりと明示しましょう。トラブルの原因になります。</small></p>
        <%= f.text_area :body, :size => "40x5", class: "col-md-12 form-control", placeholder: "なるべく具体的に書いてください。" %><br>
        <h4><%= f.label :場所 %></h4>
        <p><small>住所を詳しく書かないでください。不特定多数にあなたの住所が知られてしまいます。</small></p>
        <%= f.text_field :place, :size => 100, class: "col-md-12 form-control", placeholder: "例：小樽市稲穂町　「番地、マンション」は必要ありません。" %><br>
        <h4><%= f.label :日時（いつからいつまで） %></h4>
            <div class="row">
                <div class="col">
                    <%= f.datetime_field :datefrom, :size => 100, class: "col-md-6 form-control", placeholder: "開始地点" %>
                </div>
                <div class="col">
                    <%= f.datetime_field :dateto, :size => 100, class: "col-md-6 form-control", placeholder: "終了地点" %><br>
                </div>
            </div>
        <h4><%= f.label :必要な人数 %></h4>
        <%= f.number_field :people, :size => 100, class: "col-md-12 form-control" %><br>
        <h4><%= f.label :仕事内容 %></h4>
        <%= f.select :job, [["力仕事",1],["知識や知恵を使う仕事",2],["その他",3]], prompt: "依頼のカテゴリを選択してください", :size => 100, class: "col-md-12 form-control" %><br>
        <h4><%= f.label :画像を挿入 %></h4>
        <%= f.file_field :image, class: "col-md-12 form-control" %><br>
    <%= f.submit "発注する", class: "btn btn-primary" %><br>
    </div>

<% end %>
<%= link_to "order一覧に戻る", orders_path %><br><br><br>

app/views/orders/show.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<h3>依頼詳細</h3>
<div class="orders-container">
    <div class="order">
        <div class="main-box">
            <div class="left-container", class: "col-md-12 form-control">
                <p><%= @order.id %></p>
                <h4><%= @order.title %></h4>
                <p><%= @order.body %></p>
                <p><%= @order.place %></p>
                <p><%= @order.datefrom %>～<%= @order.dateto %></p>
                <p><%= @order.job %></p>
            </div>
            <div class="right-container", class: "col-md-4 form-control">
                <p><%= @order.created_at %></p>
                <% if requester_signed_in? && current_requester.id == @order.requester_id %>
                <%= button_to "編集する", edit_order_path(@order.id), class: "btn btn-primary" %>
                <%= button_to "依頼を取り消す", order_path(@order.id), method: :delete, class: "btn btn-primary" %>
                <% if requester_signed_in? %>
                    <% if current_requester.already_liked?(@order) %>
                        <%= button_to order_like_path(@order), class: "btn btn-primary", method: :delete do %>
                            <p>いいねを取り消す</p>
                        <% end %><br>
                    <% else %>
                        <%= button_to order_likes_path(@order), class: "btn btn-primary", method: :post do %>
                            <p>いいね</p>
                        <% end %><br>
                    <% end %>
                <% else %>
                    <p>いいねの数 = </p><%= @order.likes.count %><br>
                <% end %>
                
                <% @order.liked_requesters.each do |requester| %>
                    <li><%= requester.name %></li><br>
                <% end %>
                <% if student_signed_in? %>
                    <% if current_student.already_favorited?(@order) %>
                        <%= button_to order_favorite_path(@order), method: :delete do %>
                        <p>受注を取り消す</p><%= @order.favorites.count %>
                        <% end %>
                    <% else %>
                        <%= button_to order_favorites_path(@order), method: :post do %>
                        <p>受注</p><%= @order.favorites.count %>
                        <% end %>
                    <% end %>
                <% else %>
                    <p>受注した人数<%= @order.favorites.count %>（<%= @order.people %>人中）</p>
                <% end %>
            </div>
        </div>

        <h2>受注した商大生 </h2>
            <% @order.favorited_students.each do |student| %>
            <li><%= student.name %></li>
        <% end %>
    </div>
</div>

<%= button_to "orders", orders_path %>
<% end %>