config/routes.rb
Rails.application.routes.draw do
  root 'hello#index'
  post 'orders/:id' => 'orders#show',as: 'order'
  post 'orders/:id/edit' => 'orders#edit', as:'edit_order'
  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]

  devise_for :requesters, controllers: {
    sessions:       'requesters/sessions',
    passwords:      'requesters/passwords',
    registrations:  'requesters/registrations'
  }
  resources :requesters, only: [:index, :show, :edit, :update]
  

  resources :orders do
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :rooms, :only => [:create, :show] do
  resources :messages, :only => [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :requester
  belongs_to :student
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :order
  belongs_to :student
  validates_uniqueness_of :order_id, scope: :student_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :order
  belongs_to :requester

  validates_uniqueness_of :order_id, scope: :requester_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :requester
    has_many :likes, dependent: :destroy
    has_many :liked_requesters, through: :likes, source: :requester
    has_many :favorites, dependent: :destroy
    has_many :favorited_students, through: :favorites, source: :student
    mount_uploader :image, ImageUploader
end

app/models/receive.rb
class Receive < ApplicationRecord
  belongs_to :order
  belongs_to :student
  validates_uniqueness_of :order_id, scope: :student_id
end

app/models/requester.rb
class Requester < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_orders, through: :likes, source: :order
  has_many :rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def already_liked?(order)
    self.likes.exists?(order_id: order.id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_orders, through: :likes, source: :order
  has_many :rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_orders, through: :favorites, source: :order

  def already_liked?(order)
    self.likes.exists?(order_id: order.id)
  end

  def already_favorited?(order)
    self.favorites.exists?(order_id: order.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end

    def link
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/requesters_helper.rb
module RequestersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Srental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>商大生レンタル掲示板</h1>
        <div class="header-list">
          <ul>
            <% if requester_signed_in? or student_signed_in? %>
              <li><%= link_to "ホーム", orders_path %></li>
            <% end %>
            <% if requester_signed_in? %>
              <li><%= link_to "新しく依頼する",new_order_path %></li>
            <% end %>
          </ul>
        </div>
    </header>
    <main>
      <%= yield %>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </main>
    <footer>
      <p>Copyright © PoRtaru All Rights Reserved.</p>
    </footer>
  </body>
</html>